name: 2026-01 Demo
### example integration for Hunted Labs Entercept in a pipeline

on:
  ### UNCOMMENT THIS SECTION TO AUTOBUILD ON ANY PUSH
  #push:
  #  branches:
  #    - main
  ### UNCOMMENT THIS SECTION TO BUILD ON A REGULAR SCHEDULE
  #schedule:
  #  - cron: '38 23 */14 * *'
  ### UNCOMMENT THIS SECTION TO ENABLE ON-DEMAND BUILDS
  workflow_dispatch:
    inputs:
      mode:
        description: 'On-Demand Distributed Scan'  
        
env:
  REGISTRY: ghcr.io
  DEPSDIVER_TOKEN: ${{ secrets.DEPSDIVER_TOKEN }}
     
jobs:

  Build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write
    steps:
        
    - name: "Set IMAGE Environmental Variable"
      run: |
        echo "IMAGE=${REGISTRY}/${GITHUB_REPOSITORY}:${GITHUB_REF_NAME}" >> $GITHUB_ENV        
    - name: "Checkout Code"
      uses: actions/checkout@v4
    - name: "Log in to the Container Registry"
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}            
    - name: "Set up Docker Buildx"
      uses: docker/setup-buildx-action@v2
    - name: "Build Local Container"
      uses: docker/build-push-action@v3
      with:
        tags: ${{ env.IMAGE }}
        push: true
        load: false      

  ImageTest:
    runs-on: ubuntu-latest
    needs: Build
    steps:
    - name: "Set IMAGE Environmental Variable"
      run: |
        echo "IMAGE=${REGISTRY}/${GITHUB_REPOSITORY}:${GITHUB_REF_NAME}" >> $GITHUB_ENV
    - name: "Checkout Code"
      uses: actions/checkout@v4                
    - name: "install tools"
      run: |
        curl -sSfL https://get.anchore.io/syft | sudo sh -s -- -b ~/.local/bin
        curl -sSfL https://get.anchore.io/grype | sudo sh -s -- -b ~/.local/bin
        #curl -sSfL https://get.depsdiver.com/comrade | sudo sh -s -- -b ~/.local/bin        
    - name: "Log in to the Container Registry"
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}      
    - name: "Scan Image"
      run: |
        syft -o json ${IMAGE} > sbom.json
        grype sbom:./sbom.json
        cat scan.txt
        #comrade --token ${DEPSDIVER_TOKEN} --fail-on foci sbom:./sbom.json
